### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [Lieiad/ProyectoFinalBioinf2017-II#1]
¿O sea tu idea es en vez de utilizar Geneious repetir los análisis utilizando herramientas de software libre?

Si es así está bien, pero recuerda debes incluir herrameitnas de línea de comando como las que hemos visto en clase

**Comment by Lieiad** [comment]
Hola, Alicia y Azalea. Sí, justo es obtener ensamblajes de novo pero usando software libre desde línea de comando. El artículo de donde voy a sacar los datos (Zhang et al) tiene un método muy mal explicado. No dicen la versión del software, ni los parámetros. Me voy a basar más en el método de Ripma et al.

**Comment by Lieiad** [comment]
Incluí en el .md un pequeño comentario de que será usando software libre desde terminal.
Saludos.

**Comment by AliciaMstt** [comment]
OK :)

**Comment by AzaleaGuerra** [comment]
¡Suena padre!
