### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [Lieiad/ProyectoFinalBioinf2017-II#2]
Me parece bien que sacrifiques cantidad de análisis por dominar los pasos iniciales y entender bien qué es lo que están haciendo. También está bien que te enfoques en los datos de Zhang.

Respecto a la gráfica, puedes presentar cosas sencillas de los pasos iniciales, como un vistazo a los reads por muestra o gráficas de resumen para describir los datos.

**Comment by Lieiad** [comment]
Hola, Alicia. Perdona por contestar hasta ahora. Estuve pendiente de tus comentarios, pero me he peleado un tanto con la compu. Velvet en su manual decía que un mínimo de 12 GB de RAM estaba bien para empezar, mi compu tiene 8 GB y, ahora que empecé a hacer los análisis en serio, lleva en la construcción de la tabla de k-meros unos dos días, sólo para la primera secuencia. De ahí debe pasar a crear la gráfica de Bruijin con velvetg. Definitivamente emplearé pocas secuencias y haré el gráfico que sugieres.

Muchas gracias.

Saludos.
