### ISSUE TITLE
comentarios avances 3

### ISSUE THREAD

**Issue by AliciaMstt** [Lieiad/ProyectoFinalBioinf2017-II#3]
Me hiciste reír. Gracias. Lo necesitaba.

Suerte con lo que falta. El README va bien.

**Comment by Lieiad** [comment]
Y yo que sentí que se acababa el mundo cuando noté la falta de recursos informáticos para un genoma de angiosperma. Seguiré entonces con las bacterias.

Gracias y saludos.
